# Generated by Django 4.2.1 on 2023-08-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counsel", "0003_alter_client_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentreply",
            options={"ordering": ("date",)},
        ),
        migrations.AddField(
            model_name="client",
            name="image",
            field=models.ImageField(blank=True, upload_to="client/%Y/%m/%d"),
        ),
        migrations.AddField(
            model_name="counsellor",
            name="image",
            field=models.ImageField(blank=True, upload_to="counsellor/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="commentreply",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
