# Generated by Django 4.2.1 on 2023-08-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counsel", "0004_alter_commentreply_options_client_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="image",
            field=models.ImageField(null=True, upload_to="client/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="counsellor",
            name="image",
            field=models.ImageField(null=True, upload_to="counsellor/%Y/%m/%d"),
        ),
    ]
