# Generated by Django 4.1.6 on 2023-08-28 23:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("counsel", "0005_alter_client_image_alter_counsellor_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="counsellor",
            name="instagram",
        ),
        migrations.AlterField(
            model_name="counsellor",
            name="contact",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="counsellor",
            name="twitter",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="counsellor",
            name="website",
            field=models.URLField(null=True),
        ),
    ]
