# Generated by Django 4.1.6 on 2023-08-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "counsel",
            "0006_remove_counsellor_instagram_alter_counsellor_contact_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="counsellor",
            name="story",
        ),
        migrations.AddField(
            model_name="counsellor",
            name="whatsapp",
            field=models.URLField(null=True),
        ),
    ]
