# Generated by Django 4.1.6 on 2023-08-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counsel", "0007_remove_counsellor_story_counsellor_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="counsellor",
            name="meet",
            field=models.TextField(null=True),
        ),
    ]
