# Generated by Django 4.1.6 on 2023-08-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counsel", "0008_counsellor_meet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counsellor",
            name="meet",
            field=models.URLField(null=True),
        ),
    ]
